

import sys
import sqlite3 as lite
import random
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(500, 800)
        MainWindow.setMaximumSize(QtCore.QSize(500, 800))
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.lblSoruSayisi = QtGui.QLabel(self.centralwidget)
        self.lblSoruSayisi.setGeometry(QtCore.QRect(9, 9, 118, 16))
        self.lblSoruSayisi.setObjectName(_fromUtf8("lblSoruSayisi"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 121, 481, 631))
        self.scrollArea.setVisible(False)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 462, 1211))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.groupBox_1 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_1.setEnabled(True)
        self.groupBox_1.setObjectName(_fromUtf8("groupBox_1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.cbZorluk1 = QtGui.QComboBox(self.groupBox_1)
        self.cbZorluk1.setEnabled(True)
        self.cbZorluk1.setObjectName(_fromUtf8("cbZorluk1"))
        self.gridLayout_3.addWidget(self.cbZorluk1, 0, 0, 1, 1)
        self.cbKonu1 = QtGui.QComboBox(self.groupBox_1)
        self.cbKonu1.setObjectName(_fromUtf8("cbKonu1"))
        self.gridLayout_3.addWidget(self.cbKonu1, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_1, 1, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.cbZorluk2 = QtGui.QComboBox(self.groupBox_2)
        self.cbZorluk2.setObjectName(_fromUtf8("cbZorluk2"))
        self.gridLayout_4.addWidget(self.cbZorluk2, 0, 0, 1, 1)
        self.cbKonu2 = QtGui.QComboBox(self.groupBox_2)
        self.cbKonu2.setObjectName(_fromUtf8("cbKonu2"))
        self.gridLayout_4.addWidget(self.cbKonu2, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 2, 0, 1, 2)
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.cbZorluk3 = QtGui.QComboBox(self.groupBox_3)
        self.cbZorluk3.setObjectName(_fromUtf8("cbZorluk3"))
        self.gridLayout_5.addWidget(self.cbZorluk3, 0, 0, 1, 1)
        self.cbKonu3 = QtGui.QComboBox(self.groupBox_3)
        self.cbKonu3.setObjectName(_fromUtf8("cbKonu3"))
        self.gridLayout_5.addWidget(self.cbKonu3, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 3, 0, 1, 2)
        self.groupBox_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.cbZorluk4 = QtGui.QComboBox(self.groupBox_4)
        self.cbZorluk4.setObjectName(_fromUtf8("cbZorluk4"))
        self.gridLayout_6.addWidget(self.cbZorluk4, 0, 0, 1, 1)
        self.cbKonu4 = QtGui.QComboBox(self.groupBox_4)
        self.cbKonu4.setObjectName(_fromUtf8("cbKonu4"))
        self.gridLayout_6.addWidget(self.cbKonu4, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 4, 0, 1, 2)
        self.groupBox_5 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.cbZorluk5 = QtGui.QComboBox(self.groupBox_5)
        self.cbZorluk5.setObjectName(_fromUtf8("cbZorluk5"))
        self.gridLayout_7.addWidget(self.cbZorluk5, 0, 0, 1, 1)
        self.cbKonu5 = QtGui.QComboBox(self.groupBox_5)
        self.cbKonu5.setObjectName(_fromUtf8("cbKonu5"))
        self.gridLayout_7.addWidget(self.cbKonu5, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_5, 5, 0, 1, 2)
        self.groupBox_6 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.cbZorluk6 = QtGui.QComboBox(self.groupBox_6)
        self.cbZorluk6.setObjectName(_fromUtf8("cbZorluk6"))
        self.gridLayout_8.addWidget(self.cbZorluk6, 0, 0, 1, 1)
        self.cbKonu6 = QtGui.QComboBox(self.groupBox_6)
        self.cbKonu6.setObjectName(_fromUtf8("cbKonu6"))
        self.gridLayout_8.addWidget(self.cbKonu6, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_6, 6, 0, 1, 2)
        self.groupBox_7 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.cbZorluk7 = QtGui.QComboBox(self.groupBox_7)
        self.cbZorluk7.setObjectName(_fromUtf8("cbZorluk7"))
        self.gridLayout_9.addWidget(self.cbZorluk7, 0, 0, 1, 1)
        self.cbKonu7 = QtGui.QComboBox(self.groupBox_7)
        self.cbKonu7.setObjectName(_fromUtf8("cbKonu7"))
        self.gridLayout_9.addWidget(self.cbKonu7, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_7, 7, 0, 1, 2)
        self.groupBox_8 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.cbZorluk8 = QtGui.QComboBox(self.groupBox_8)
        self.cbZorluk8.setObjectName(_fromUtf8("cbZorluk8"))
        self.gridLayout_10.addWidget(self.cbZorluk8, 0, 0, 1, 1)
        self.cbKonu8 = QtGui.QComboBox(self.groupBox_8)
        self.cbKonu8.setObjectName(_fromUtf8("cbKonu8"))
        self.gridLayout_10.addWidget(self.cbKonu8, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_8, 8, 0, 1, 2)
        self.groupBox_9 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.cbZorluk9 = QtGui.QComboBox(self.groupBox_9)
        self.cbZorluk9.setObjectName(_fromUtf8("cbZorluk9"))
        self.gridLayout_11.addWidget(self.cbZorluk9, 0, 0, 1, 1)
        self.cbKonu9 = QtGui.QComboBox(self.groupBox_9)
        self.cbKonu9.setObjectName(_fromUtf8("cbKonu9"))
        self.gridLayout_11.addWidget(self.cbKonu9, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_9, 9, 0, 1, 2)
        self.groupBox_10 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.cbZorluk10 = QtGui.QComboBox(self.groupBox_10)
        self.cbZorluk10.setObjectName(_fromUtf8("cbZorluk10"))
        self.gridLayout_12.addWidget(self.cbZorluk10, 0, 0, 1, 1)
        self.cbKonu10 = QtGui.QComboBox(self.groupBox_10)
        self.cbKonu10.setObjectName(_fromUtf8("cbKonu10"))
        self.gridLayout_12.addWidget(self.cbKonu10, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_10, 10, 0, 1, 2)
        self.groupBox_11 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_11)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.cbZorluk11 = QtGui.QComboBox(self.groupBox_11)
        self.cbZorluk11.setObjectName(_fromUtf8("cbZorluk11"))
        self.gridLayout_13.addWidget(self.cbZorluk11, 0, 0, 1, 1)
        self.cbKonu11 = QtGui.QComboBox(self.groupBox_11)
        self.cbKonu11.setObjectName(_fromUtf8("cbKonu11"))
        self.gridLayout_13.addWidget(self.cbKonu11, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_11, 11, 0, 1, 2)
        self.groupBox_12 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.gridLayout_14 = QtGui.QGridLayout(self.groupBox_12)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.cbZorluk12 = QtGui.QComboBox(self.groupBox_12)
        self.cbZorluk12.setObjectName(_fromUtf8("cbZorluk12"))
        self.gridLayout_14.addWidget(self.cbZorluk12, 0, 0, 1, 1)
        self.cbKonu12 = QtGui.QComboBox(self.groupBox_12)
        self.cbKonu12.setObjectName(_fromUtf8("cbKonu12"))
        self.gridLayout_14.addWidget(self.cbKonu12, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_12, 12, 0, 1, 2)
        self.groupBox_13 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox_13)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.cbZorluk13 = QtGui.QComboBox(self.groupBox_13)
        self.cbZorluk13.setObjectName(_fromUtf8("cbZorluk13"))
        self.gridLayout_15.addWidget(self.cbZorluk13, 0, 0, 1, 1)
        self.cbKonu13 = QtGui.QComboBox(self.groupBox_13)
        self.cbKonu13.setObjectName(_fromUtf8("cbKonu13"))
        self.gridLayout_15.addWidget(self.cbKonu13, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_13, 13, 0, 1, 2)
        self.groupBox_15 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBox_15)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.cbZorluk15 = QtGui.QComboBox(self.groupBox_15)
        self.cbZorluk15.setObjectName(_fromUtf8("cbZorluk15"))
        self.gridLayout_17.addWidget(self.cbZorluk15, 0, 0, 1, 1)
        self.cbKonu15 = QtGui.QComboBox(self.groupBox_15)
        self.cbKonu15.setObjectName(_fromUtf8("cbKonu15"))
        self.gridLayout_17.addWidget(self.cbKonu15, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_15, 15, 0, 1, 2)
        self.groupBox_16 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.gridLayout_18 = QtGui.QGridLayout(self.groupBox_16)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.cbZorluk16 = QtGui.QComboBox(self.groupBox_16)
        self.cbZorluk16.setObjectName(_fromUtf8("cbZorluk16"))
        self.gridLayout_18.addWidget(self.cbZorluk16, 0, 0, 1, 1)
        self.cbKonu16 = QtGui.QComboBox(self.groupBox_16)
        self.cbKonu16.setObjectName(_fromUtf8("cbKonu16"))
        self.gridLayout_18.addWidget(self.cbKonu16, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_16, 16, 0, 1, 2)
        self.groupBox_17 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.gridLayout_19 = QtGui.QGridLayout(self.groupBox_17)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.cbZorluk17 = QtGui.QComboBox(self.groupBox_17)
        self.cbZorluk17.setObjectName(_fromUtf8("cbZorluk17"))
        self.gridLayout_19.addWidget(self.cbZorluk17, 0, 0, 1, 1)
        self.cbKonu17 = QtGui.QComboBox(self.groupBox_17)
        self.cbKonu17.setObjectName(_fromUtf8("cbKonu17"))
        self.gridLayout_19.addWidget(self.cbKonu17, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_17, 17, 0, 1, 2)
        self.groupBox_18 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_18.setObjectName(_fromUtf8("groupBox_18"))
        self.gridLayout_20 = QtGui.QGridLayout(self.groupBox_18)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.cbZorluk18 = QtGui.QComboBox(self.groupBox_18)
        self.cbZorluk18.setObjectName(_fromUtf8("cbZorluk18"))
        self.gridLayout_20.addWidget(self.cbZorluk18, 0, 0, 1, 1)
        self.cbKonu18 = QtGui.QComboBox(self.groupBox_18)
        self.cbKonu18.setObjectName(_fromUtf8("cbKonu18"))
        self.gridLayout_20.addWidget(self.cbKonu18, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_18, 18, 0, 1, 2)
        self.groupBox_19 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_19.setObjectName(_fromUtf8("groupBox_19"))
        self.gridLayout_21 = QtGui.QGridLayout(self.groupBox_19)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.cbZorluk19 = QtGui.QComboBox(self.groupBox_19)
        self.cbZorluk19.setObjectName(_fromUtf8("cbZorluk19"))
        self.gridLayout_21.addWidget(self.cbZorluk19, 0, 0, 1, 1)
        self.cbKonu19 = QtGui.QComboBox(self.groupBox_19)
        self.cbKonu19.setObjectName(_fromUtf8("cbKonu19"))
        self.gridLayout_21.addWidget(self.cbKonu19, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_19, 19, 0, 1, 2)
        self.groupBox_20 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_20.setObjectName(_fromUtf8("groupBox_20"))
        self.gridLayout_22 = QtGui.QGridLayout(self.groupBox_20)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.cbZorluk20 = QtGui.QComboBox(self.groupBox_20)
        self.cbZorluk20.setObjectName(_fromUtf8("cbZorluk20"))
        self.gridLayout_22.addWidget(self.cbZorluk20, 0, 0, 1, 1)
        self.cbKonu20 = QtGui.QComboBox(self.groupBox_20)
        self.cbKonu20.setEnabled(True)
        self.cbKonu20.setObjectName(_fromUtf8("cbKonu20"))
        self.gridLayout_22.addWidget(self.cbKonu20, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_20, 20, 0, 1, 2)
        self.groupBox_14 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.gridLayout_16 = QtGui.QGridLayout(self.groupBox_14)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.cbZorluk14 = QtGui.QComboBox(self.groupBox_14)
        self.cbZorluk14.setObjectName(_fromUtf8("cbZorluk14"))
        self.gridLayout_16.addWidget(self.cbZorluk14, 0, 0, 1, 1)
        self.cbKonu14 = QtGui.QComboBox(self.groupBox_14)
        self.cbKonu14.setObjectName(_fromUtf8("cbKonu14"))
        self.gridLayout_16.addWidget(self.cbKonu14, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_14, 14, 0, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(200, 7, 77, 100))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox.setMinimum(5)
        self.spinBox.setMaximum(20)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.verticalLayout.addWidget(self.spinBox)
        self.btnSoruGir = QtGui.QPushButton(self.layoutWidget)
        self.btnSoruGir.setObjectName(_fromUtf8("btnSoruGir"))
        self.verticalLayout.addWidget(self.btnSoruGir)
        self.btnSoruOlustur = QtGui.QPushButton(self.layoutWidget)
        self.btnSoruOlustur.setObjectName(_fromUtf8("btnSoruOlustur"))
        self.verticalLayout.addWidget(self.btnSoruOlustur)
        self.scrollArea_2 = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 121, 481, 631))
        self.scrollArea_2.setVisible(False)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 109, 2212))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.formLayout = QtGui.QFormLayout(self.scrollAreaWidgetContents_2)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.groupBoxCevap_1 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxCevap_1.setObjectName(_fromUtf8("groupBoxCevap_1"))
        self.gridLayout = QtGui.QGridLayout(self.groupBoxCevap_1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.txtSoru1 = QtGui.QPlainTextEdit(self.groupBoxCevap_1)
        self.txtSoru1.setEnabled(False)
        self.txtSoru1.setObjectName(_fromUtf8("txtSoru1"))
        self.gridLayout.addWidget(self.txtSoru1, 0, 0, 1, 1)
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.groupBoxCevap_1)
        self.groupBoxCevap_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxCevap_2.setObjectName(_fromUtf8("groupBoxCevap_2"))
        self.gridLayout_23 = QtGui.QGridLayout(self.groupBoxCevap_2)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.txtSoru2 = QtGui.QPlainTextEdit(self.groupBoxCevap_2)
        self.txtSoru2.setEnabled(False)
        self.txtSoru2.setObjectName(_fromUtf8("txtSoru2"))
        self.gridLayout_23.addWidget(self.txtSoru2, 0, 0, 1, 1)
        self.formLayout.setWidget(1, QtGui.QFormLayout.SpanningRole, self.groupBoxCevap_2)
        self.groupBoxCevap_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxCevap_3.setObjectName(_fromUtf8("groupBoxCevap_3"))
        self.gridLayout_24 = QtGui.QGridLayout(self.groupBoxCevap_3)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.txtSoru3 = QtGui.QPlainTextEdit(self.groupBoxCevap_3)
        self.txtSoru3.setEnabled(False)
        self.txtSoru3.setObjectName(_fromUtf8("txtSoru3"))
        self.gridLayout_24.addWidget(self.txtSoru3, 0, 0, 1, 1)
        self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.groupBoxCevap_3)
        self.groupBoxCevap_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxCevap_4.setObjectName(_fromUtf8("groupBoxCevap_4"))
        self.gridLayout_25 = QtGui.QGridLayout(self.groupBoxCevap_4)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.txtSoru4 = QtGui.QPlainTextEdit(self.groupBoxCevap_4)
        self.txtSoru4.setEnabled(False)
        self.txtSoru4.setObjectName(_fromUtf8("txtSoru4"))
        self.gridLayout_25.addWidget(self.txtSoru4, 0, 0, 1, 1)
        self.formLayout.setWidget(3, QtGui.QFormLayout.SpanningRole, self.groupBoxCevap_4)
        self.groupBoxCevap_5 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxCevap_5.setObjectName(_fromUtf8("groupBoxCevap_5"))
        self.gridLayout_27 = QtGui.QGridLayout(self.groupBoxCevap_5)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.txtSoru5 = QtGui.QPlainTextEdit(self.groupBoxCevap_5)
        self.txtSoru5.setEnabled(False)
        self.txtSoru5.setObjectName(_fromUtf8("txtSoru5"))
        self.gridLayout_27.addWidget(self.txtSoru5, 0, 0, 1, 1)
        self.formLayout.setWidget(4, QtGui.QFormLayout.SpanningRole, self.groupBoxCevap_5)
        self.groupBoxCevap_6 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxCevap_6.setObjectName(_fromUtf8("groupBoxCevap_6"))
        self.gridLayout_28 = QtGui.QGridLayout(self.groupBoxCevap_6)
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        self.txtSoru6 = QtGui.QPlainTextEdit(self.groupBoxCevap_6)
        self.txtSoru6.setEnabled(False)
        self.txtSoru6.setObjectName(_fromUtf8("txtSoru6"))
        self.gridLayout_28.addWidget(self.txtSoru6, 0, 0, 1, 1)
        self.formLayout.setWidget(5, QtGui.QFormLayout.SpanningRole, self.groupBoxCevap_6)
        self.groupBoxCevap_7 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxCevap_7.setObjectName(_fromUtf8("groupBoxCevap_7"))
        self.gridLayout_29 = QtGui.QGridLayout(self.groupBoxCevap_7)
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.txtSoru7 = QtGui.QPlainTextEdit(self.groupBoxCevap_7)
        self.txtSoru7.setEnabled(False)
        self.txtSoru7.setObjectName(_fromUtf8("txtSoru7"))
        self.gridLayout_29.addWidget(self.txtSoru7, 0, 0, 1, 1)
        self.formLayout.setWidget(6, QtGui.QFormLayout.SpanningRole, self.groupBoxCevap_7)
        self.groupBoxCevap_8 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxCevap_8.setObjectName(_fromUtf8("groupBoxCevap_8"))
        self.gridLayout_30 = QtGui.QGridLayout(self.groupBoxCevap_8)
        self.gridLayout_30.setObjectName(_fromUtf8("gridLayout_30"))
        self.txtSoru8 = QtGui.QPlainTextEdit(self.groupBoxCevap_8)
        self.txtSoru8.setEnabled(False)
        self.txtSoru8.setObjectName(_fromUtf8("txtSoru8"))
        self.gridLayout_30.addWidget(self.txtSoru8, 0, 0, 1, 1)
        self.formLayout.setWidget(7, QtGui.QFormLayout.SpanningRole, self.groupBoxCevap_8)
        self.groupBoxCevap_9 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxCevap_9.setObjectName(_fromUtf8("groupBoxCevap_9"))
        self.gridLayout_31 = QtGui.QGridLayout(self.groupBoxCevap_9)
        self.gridLayout_31.setObjectName(_fromUtf8("gridLayout_31"))
        self.txtSoru9 = QtGui.QPlainTextEdit(self.groupBoxCevap_9)
        self.txtSoru9.setEnabled(False)
        self.txtSoru9.setObjectName(_fromUtf8("txtSoru9"))
        self.gridLayout_31.addWidget(self.txtSoru9, 0, 0, 1, 1)
        self.formLayout.setWidget(8, QtGui.QFormLayout.SpanningRole, self.groupBoxCevap_9)
        self.groupBoxCevap_10 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxCevap_10.setObjectName(_fromUtf8("groupBoxCevap_10"))
        self.gridLayout_32 = QtGui.QGridLayout(self.groupBoxCevap_10)
        self.gridLayout_32.setObjectName(_fromUtf8("gridLayout_32"))
        self.txtSoru10 = QtGui.QPlainTextEdit(self.groupBoxCevap_10)
        self.txtSoru10.setEnabled(False)
        self.txtSoru10.setObjectName(_fromUtf8("txtSoru10"))
        self.gridLayout_32.addWidget(self.txtSoru10, 0, 0, 1, 1)
        self.formLayout.setWidget(9, QtGui.QFormLayout.SpanningRole, self.groupBoxCevap_10)
        self.groupBoxCevap_11 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxCevap_11.setObjectName(_fromUtf8("groupBoxCevap_11"))
        self.gridLayout_33 = QtGui.QGridLayout(self.groupBoxCevap_11)
        self.gridLayout_33.setObjectName(_fromUtf8("gridLayout_33"))
        self.txtSoru11 = QtGui.QPlainTextEdit(self.groupBoxCevap_11)
        self.txtSoru11.setEnabled(False)
        self.txtSoru11.setObjectName(_fromUtf8("txtSoru11"))
        self.gridLayout_33.addWidget(self.txtSoru11, 0, 0, 1, 1)
        self.formLayout.setWidget(10, QtGui.QFormLayout.SpanningRole, self.groupBoxCevap_11)
        self.groupBoxCevap_12 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxCevap_12.setObjectName(_fromUtf8("groupBoxCevap_12"))
        self.gridLayout_34 = QtGui.QGridLayout(self.groupBoxCevap_12)
        self.gridLayout_34.setObjectName(_fromUtf8("gridLayout_34"))
        self.txtSoru12 = QtGui.QPlainTextEdit(self.groupBoxCevap_12)
        self.txtSoru12.setEnabled(False)
        self.txtSoru12.setObjectName(_fromUtf8("txtSoru12"))
        self.gridLayout_34.addWidget(self.txtSoru12, 0, 0, 1, 1)
        self.formLayout.setWidget(11, QtGui.QFormLayout.SpanningRole, self.groupBoxCevap_12)
        self.groupBoxCevap_13 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxCevap_13.setObjectName(_fromUtf8("groupBoxCevap_13"))
        self.gridLayout_35 = QtGui.QGridLayout(self.groupBoxCevap_13)
        self.gridLayout_35.setObjectName(_fromUtf8("gridLayout_35"))
        self.txtSoru13 = QtGui.QPlainTextEdit(self.groupBoxCevap_13)
        self.txtSoru13.setEnabled(False)
        self.txtSoru13.setObjectName(_fromUtf8("txtSoru13"))
        self.gridLayout_35.addWidget(self.txtSoru13, 0, 0, 1, 1)
        self.formLayout.setWidget(12, QtGui.QFormLayout.SpanningRole, self.groupBoxCevap_13)
        self.groupBoxCevap_14 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxCevap_14.setObjectName(_fromUtf8("groupBoxCevap_14"))
        self.gridLayout_37 = QtGui.QGridLayout(self.groupBoxCevap_14)
        self.gridLayout_37.setObjectName(_fromUtf8("gridLayout_37"))
        self.txtSoru14 = QtGui.QPlainTextEdit(self.groupBoxCevap_14)
        self.txtSoru14.setEnabled(False)
        self.txtSoru14.setObjectName(_fromUtf8("txtSoru14"))
        self.gridLayout_37.addWidget(self.txtSoru14, 0, 0, 1, 1)
        self.formLayout.setWidget(13, QtGui.QFormLayout.SpanningRole, self.groupBoxCevap_14)
        self.groupBoxCevap_15 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxCevap_15.setObjectName(_fromUtf8("groupBoxCevap_15"))
        self.gridLayout_36 = QtGui.QGridLayout(self.groupBoxCevap_15)
        self.gridLayout_36.setObjectName(_fromUtf8("gridLayout_36"))
        self.txtSoru15 = QtGui.QPlainTextEdit(self.groupBoxCevap_15)
        self.txtSoru15.setEnabled(False)
        self.txtSoru15.setObjectName(_fromUtf8("txtSoru15"))
        self.gridLayout_36.addWidget(self.txtSoru15, 0, 0, 1, 1)
        self.formLayout.setWidget(14, QtGui.QFormLayout.SpanningRole, self.groupBoxCevap_15)
        self.groupBoxCevap_16 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxCevap_16.setObjectName(_fromUtf8("groupBoxCevap_16"))
        self.gridLayout_38 = QtGui.QGridLayout(self.groupBoxCevap_16)
        self.gridLayout_38.setObjectName(_fromUtf8("gridLayout_38"))
        self.txtSoru16 = QtGui.QPlainTextEdit(self.groupBoxCevap_16)
        self.txtSoru16.setEnabled(False)
        self.txtSoru16.setObjectName(_fromUtf8("txtSoru16"))
        self.gridLayout_38.addWidget(self.txtSoru16, 0, 0, 1, 1)
        self.formLayout.setWidget(15, QtGui.QFormLayout.SpanningRole, self.groupBoxCevap_16)
        self.groupBoxCevap_17 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxCevap_17.setObjectName(_fromUtf8("groupBoxCevap_17"))
        self.gridLayout_39 = QtGui.QGridLayout(self.groupBoxCevap_17)
        self.gridLayout_39.setObjectName(_fromUtf8("gridLayout_39"))
        self.txtSoru17 = QtGui.QPlainTextEdit(self.groupBoxCevap_17)
        self.txtSoru17.setEnabled(False)
        self.txtSoru17.setObjectName(_fromUtf8("txtSoru17"))
        self.gridLayout_39.addWidget(self.txtSoru17, 0, 0, 1, 1)
        self.formLayout.setWidget(16, QtGui.QFormLayout.SpanningRole, self.groupBoxCevap_17)
        self.groupBoxCevap_18 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxCevap_18.setObjectName(_fromUtf8("groupBoxCevap_18"))
        self.gridLayout_40 = QtGui.QGridLayout(self.groupBoxCevap_18)
        self.gridLayout_40.setObjectName(_fromUtf8("gridLayout_40"))
        self.txtSoru18 = QtGui.QPlainTextEdit(self.groupBoxCevap_18)
        self.txtSoru18.setEnabled(False)
        self.txtSoru18.setObjectName(_fromUtf8("txtSoru18"))
        self.gridLayout_40.addWidget(self.txtSoru18, 0, 0, 1, 1)
        self.formLayout.setWidget(17, QtGui.QFormLayout.SpanningRole, self.groupBoxCevap_18)
        self.groupBoxCevap_19 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxCevap_19.setObjectName(_fromUtf8("groupBoxCevap_19"))
        self.gridLayout_41 = QtGui.QGridLayout(self.groupBoxCevap_19)
        self.gridLayout_41.setObjectName(_fromUtf8("gridLayout_41"))
        self.txtSoru19 = QtGui.QPlainTextEdit(self.groupBoxCevap_19)
        self.txtSoru19.setEnabled(False)
        self.txtSoru19.setObjectName(_fromUtf8("txtSoru19"))
        self.gridLayout_41.addWidget(self.txtSoru19, 0, 0, 1, 1)
        self.formLayout.setWidget(18, QtGui.QFormLayout.SpanningRole, self.groupBoxCevap_19)
        self.groupBoxCevap_20 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBoxCevap_20.setObjectName(_fromUtf8("groupBoxCevap_20"))
        self.gridLayout_42 = QtGui.QGridLayout(self.groupBoxCevap_20)
        self.gridLayout_42.setObjectName(_fromUtf8("gridLayout_42"))
        self.txtSoru20 = QtGui.QPlainTextEdit(self.groupBoxCevap_20)
        self.txtSoru20.setEnabled(False)
        self.txtSoru20.setObjectName(_fromUtf8("txtSoru20"))
        self.gridLayout_42.addWidget(self.txtSoru20, 0, 0, 1, 1)
        self.formLayout.setWidget(19, QtGui.QFormLayout.SpanningRole, self.groupBoxCevap_20)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Sınav Sorusu Formu", None))
        self.lblSoruSayisi.setText(_translate("MainWindow", "Lütfen soru sayısı giriniz:", None))
        self.label.setText(_translate("MainWindow", "Zorluk", None))
        self.label_2.setText(_translate("MainWindow", "Konu", None))
        self.groupBox_1.setTitle(_translate("MainWindow", "1", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "2", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "3", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "4", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "5", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "6", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "7", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "8", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "9", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "10", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "11", None))
        self.groupBox_12.setTitle(_translate("MainWindow", "12", None))
        self.groupBox_13.setTitle(_translate("MainWindow", "13", None))
        self.groupBox_15.setTitle(_translate("MainWindow", "15", None))
        self.groupBox_16.setTitle(_translate("MainWindow", "16", None))
        self.groupBox_17.setTitle(_translate("MainWindow", "17", None))
        self.groupBox_18.setTitle(_translate("MainWindow", "18", None))
        self.groupBox_19.setTitle(_translate("MainWindow", "19", None))
        self.groupBox_20.setTitle(_translate("MainWindow", "20", None))
        self.groupBox_14.setTitle(_translate("MainWindow", "14", None))
        self.btnSoruGir.setText(_translate("MainWindow", "Gir", None))
        self.btnSoruOlustur.setText(_translate("MainWindow", "Olustur", None))
        self.groupBoxCevap_1.setTitle(_translate("MainWindow", "1", None))
        self.groupBoxCevap_2.setTitle(_translate("MainWindow", "2", None))
        self.groupBoxCevap_3.setTitle(_translate("MainWindow", "3", None))
        self.groupBoxCevap_4.setTitle(_translate("MainWindow", "4", None))
        self.groupBoxCevap_5.setTitle(_translate("MainWindow", "5", None))
        self.groupBoxCevap_6.setTitle(_translate("MainWindow", "6", None))
        self.groupBoxCevap_7.setTitle(_translate("MainWindow", "7", None))
        self.groupBoxCevap_8.setTitle(_translate("MainWindow", "8", None))
        self.groupBoxCevap_9.setTitle(_translate("MainWindow", "9", None))
        self.groupBoxCevap_10.setTitle(_translate("MainWindow", "10", None))
        self.groupBoxCevap_11.setTitle(_translate("MainWindow", "11", None))
        self.groupBoxCevap_12.setTitle(_translate("MainWindow", "12", None))
        self.groupBoxCevap_13.setTitle(_translate("MainWindow", "13", None))
        self.groupBoxCevap_14.setTitle(_translate("MainWindow", "14", None))
        self.groupBoxCevap_15.setTitle(_translate("MainWindow", "15", None))
        self.groupBoxCevap_16.setTitle(_translate("MainWindow", "16", None))
        self.groupBoxCevap_17.setTitle(_translate("MainWindow", "17", None))
        self.groupBoxCevap_18.setTitle(_translate("MainWindow", "18", None))
        self.groupBoxCevap_19.setTitle(_translate("MainWindow", "19", None))
        self.groupBoxCevap_20.setTitle(_translate("MainWindow", "20", None))

#Veritabanından alınan verinin, python üzerinde temsil edilmesini sağlayan sınıf yapısı.
class SoruObject():
    def __init__(self):
        self.soruIcerik = ""
        self.soruZorluk = ""
        self.id = 0
        self.konu = ""

#Verinin SQLite veritabanından çekilerek, program ekranına yansıtılması için kullanılan sınıf yapısıdır.
class SQLiteLogic():

    def __init__(self, Ui_MainWindow):
        self.ui = Ui_MainWindow

    #Veritabanında tanımlanmış zorluk ve konu değerlerini alarak, program ekranındaki ilgili combobox kontrollerini besler.
    def fillZorlukVeKonu(self):

        maxSoruSayisi = int(ui.spinBox.maximum())

        try:
            connection = lite.connect("ders.db")
            cursor = connection.cursor()
            cursor.execute("select distinct SoruZorluk from tbl_SoruBankasi")
            data = cursor.fetchall()

            zorlukArray = []

            for ithData in data:
                ithDataValue = ithData[0]
                zorlukArray.append(ithDataValue)


            for i in range(1, maxSoruSayisi + 1):
                groupName = "groupBox_" + str(i)
                zorlukName = "cbZorluk" + str(i)
                groupChild = ui.scrollArea.findChild(QtGui.QGroupBox, groupName)
                zorlukChild = groupChild.findChild(QtGui.QComboBox, zorlukName)
                zorlukChild.addItems(zorlukArray)


            cursor.execute("select distinct Konu from tbl_SoruBankasi")
            data = cursor.fetchall()

            konuArray = []

            for ithData in data:
                ithDataValue = ithData[0]
                konuArray.append(ithDataValue)

            for i in range(1, maxSoruSayisi + 1):
                groupName = "groupBox_" + str(i)
                konuName = "cbKonu" + str(i)
                groupChild = ui.scrollArea.findChild(QtGui.QGroupBox, groupName)
                konuChild = groupChild.findChild(QtGui.QComboBox, konuName)
                konuChild.addItems(konuArray)

            cursor.close()
            connection.close()

        except:
            print("Error")
            sys.exit(1)

    #Bütün soruları veritabanından okur, "SoruObject" değeri olarak bir listeye atar. Listeyi karıştırarak döndürür.
    def sorulariAl(self):
        try:
            connection = lite.connect("ders.db")
            cursor = connection.cursor()
            cursor.execute("select SoruIcerik, SoruZorluk, Id, Konu from tbl_SoruBankasi")
            data = cursor.fetchall()
            soruIcerikler = []
            for soru in data:
                soruIcerik = SoruObject()
                soruIcerik.soruIcerik = str(soru[0])
                soruIcerik.soruZorluk = str(soru[1])
                soruIcerik.id = int(soru[2])
                soruIcerik.konu = str(soru[3])
                soruIcerikler.append(soruIcerik)
                random.shuffle(soruIcerikler)
            return soruIcerikler
        except:
            print("Error")
            sys.exit(1)

    #Verilen konu ve zorluk değerlerine göre, karşılaşılan ilk soru listeden alınır ve soru listeden silinir
    def ilkSoruyuAl(self, soruIcerikler, konu, zorluk):
        for i in range(1, len(soruIcerikler) + 1):
            j = -i
            if soruIcerikler[j].soruZorluk == zorluk and soruIcerikler[j].konu == konu:
                soruIcerik = soruIcerikler[j].soruIcerik
                del soruIcerikler[j]
                return soruIcerik

        return ""

    #Verilen soru sayısı kadar, konu ve zorluk özelliklerine göre soru listesini doldurur
    def fillSoru(self, soruSayisi):
        soruIcerikler = self.sorulariAl()
        for i in range(1, soruSayisi + 1):
            soruGroupName = "groupBoxCevap_" + str(i)
            soruName = "txtSoru" + str(i)
            groupName = "groupBox_" + str(i)
            konuName = "cbKonu" + str(i)
            zorlukName = "cbZorluk" + str(i)
            groupChild = ui.scrollArea.findChild(QtGui.QGroupBox, groupName)
            soruGroupName = ui.scrollArea_2.findChild(QtGui.QGroupBox, soruGroupName)
            konuChild = groupChild.findChild(QtGui.QComboBox, konuName)
            zorlukChild = groupChild.findChild(QtGui.QComboBox, zorlukName)
            soruChild = soruGroupName.findChild(QtGui.QPlainTextEdit, soruName)

            seciliKonuIndex = konuChild.currentIndex()
            seciliZorlukIndex = zorlukChild.currentIndex()

            seciliKonuValue = konuChild.itemText(seciliKonuIndex)
            seciliZorlukValue = zorlukChild.itemText(seciliZorlukIndex)

            soruIcerikValue = self.ilkSoruyuAl(soruIcerikler, seciliKonuValue, seciliZorlukValue)
            #ui.txtSoru1.setPlainText(soruIcerikValue)
            try:
                soruChild.setPlainText(soruIcerikValue)
            except:
                print("")

#Sınav sorularının yönetildiği ana mantık noktasıdır. Uygulama ekranındaki soru girme ve soru oluşturma butonlarına bağlanan eventleri içerir.
class SinavLogic():

    #Soru sayısı girme butonuna tıklama eventidir.
    def soruGirOnClicked(self):
        maxSoruSayisi = ui.spinBox.maximum()
        soruSayisi = ui.spinBox.value()
        for i in range(1, int(soruSayisi) + 1):
            groupName = "groupBox_" + str(i)
            groupChild = ui.scrollArea.findChild(QtGui.QGroupBox, groupName)
            groupChild.setVisible(True)

        for i in range((int(soruSayisi) + 1), int(maxSoruSayisi) + 1):
            groupName = "groupBox_" + str(i)
            groupChild = ui.scrollArea.findChild(QtGui.QGroupBox, groupName)
            groupChild.setVisible(False)

        self.secilenSoruSayisi = int(soruSayisi)
        ui.scrollArea.setVisible(True)
        ui.scrollArea_2.setVisible(False)

    #Soru oluşturma butonunun tıklama eventidir.
    def soruOlusturOnClicked(self):
        maxSoruSayisi = ui.spinBox.maximum()
        for i in range(1, self.secilenSoruSayisi + 1):
            groupName = "groupBoxCevap_" + str(i)
            groupChild = ui.scrollArea_2.findChild(QtGui.QGroupBox, groupName)
            groupChild.setVisible(True)

        for i in range(self.secilenSoruSayisi + 1, int(maxSoruSayisi) + 1):
            groupName = "groupBoxCevap_" + str(i)
            groupChild = ui.scrollArea_2.findChild(QtGui.QGroupBox, groupName)
            groupChild.setVisible(False)

        ui.scrollArea.setVisible(False)
        ui.scrollArea_2.setVisible(True)

        self.sqlite.fillSoru(self.secilenSoruSayisi)

    def __init__(self, Ui_MainWindow):
        self.ui = Ui_MainWindow
        self.secilenSoruSayisi = 0
        self.sqlite = SQLiteLogic(Ui_MainWindow)
        self.sqlite.fillZorlukVeKonu()

    #Buton tıklama eventlerinin bağlandığı fonksiyondur
    def apply(self):
        ui.btnSoruGir.clicked.connect(self.soruGirOnClicked)
        ui.btnSoruOlustur.clicked.connect(self.soruOlusturOnClicked)


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    logic = SinavLogic(ui)
    logic.apply()
    MainWindow.show()
    sys.exit(app.exec_())

